[tool.poetry]
name = "Skark_website"  # Replace with your project name
version = "0.1.0"
description = "A short description of your project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^2.2.3"  # Example dependency
requests = "^2.28.1"  # Example dependency

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
